### ISSUE TITLE
Invalid Character Error

### ISSUE THREAD

**Issue by PrivatePasta** [MrMarble/yoink#2]
Running the arm64 executable, I'm facing this error when trying to run anything:

```
yoink 0.1.1

yoink: error: invalid character '<' looking for beginning of value
```

The only command that works is print-config and as far as I can tell, it looks pretty normal. Only thing missing is the qbittorrent password, but I believe that is intentional.
Not sharing the yaml for obvious reasons

**Comment by PrivatePasta** [comment]
This is the output of print-config with all sensitive information removed:
```
yoink 0.1.1

{
  "QbitTorrent": {
    "Host": "",
    "User": "",
    "Pass": ""
  },
  "Prowlarr": {
    "Host": "",
    "APIKey": ""
  },
  "DownloadDir": "/home/ubuntu",
  "TotalFreelechSize": 100000000000,
  "Indexers": [
    {
      "ID": 20,
      "MaxSeeders": 10,
      "SeedTime": 0,
      "MaxSize": 40000000000
    }
  ],
  "Category": "PTP-FL",
  "Paused": false
}
```

**Comment by MrMarble** [comment]
Some things may be broken, as I've made this for me so "it works on my machine".
I just pushed a new release with a lot of changes, could you please try that one again and see if the error is still there?

Currently, qBitTorrent authentication is not implemented, as I have disabled the authentication for local network, that may be it. 

It's a bit late (almost 1AM), will look into it tomorrow 👍🏼

**Comment by PrivatePasta** [comment]
The original issue was caused by a trailing slash in the prowlarr URL, removing that fixed it. As for the qbittorrent thing, I guess I'll wait for that authentication update. Thanks for working on this
